import React, { useRef } from 'react';
import { View, ScrollView, Pressable } from 'react-native';
import { useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { ScreenLayout } from '@/presentation/shared/layouts/ScreenLayout';
import { AppText } from '@/presentation/shared/components/ui/AppText';
import { colors } from '@/core/theme/colors';
import { useTheme } from '@/core/theme/useTheme';

// ── Types ─────────────────────────────────────────────────────────────────────
interface PolicySection {
  title: string;
  content: string[];
}

// ── Policy content (EN) ───────────────────────────────────────────────────────
const POLICY_EN: PolicySection[] = [
  {
    title: 'Introduction',
    content: [
      'Welcome to TChecki ("we", "our", or "us"). TChecki is a mobile application designed to help users discover, review, and rate local businesses in Tunisia.',
      'This Privacy Policy explains how we collect, use, store, share, and protect your personal information when you use the TChecki mobile application and related services (collectively, the "Service").',
      'We are committed to protecting your personal data in compliance with the Tunisian Organic Law No. 2004-63 of 27 July 2004 on the Protection of Personal Data, as well as internationally recognized data protection principles.',
      'By using TChecki, you consent to the collection and use of your information as described in this Privacy Policy. If you do not agree, please discontinue use of the Service.',
    ],
  },
  {
    title: '1. Who We Are',
    content: [
      'TChecki is operated and owned by a company registered in the Republic of Tunisia.',
      'Registered Country: Republic of Tunisia',
      'Supervisory Authority: Instance Nationale de Protection des Données Personnelles (INPDP) — the national authority responsible for data protection in Tunisia.',
      'For any privacy-related inquiries, contact us at: support@tchecki.app',
    ],
  },
  {
    title: '2. Information We Collect',
    content: [
      'We collect the following categories of personal data:',
      '2.1 Account Information\n• Full name\n• Email address\n• Phone number (optional)\n• Profile picture (optional)\n• Gender (optional)\n• Date of birth (optional)\n• Account type (Simple User, Business Owner)',
      '2.2 Business Information (Business Owners only)\n• Business name\n• Business category and sub-categories\n• Business location/address\n• Business website and social media links (Facebook, Instagram)\n• Business logo and cover photo\n• Business description',
      '2.3 User-Generated Content\n• Reviews, ratings, and written comments you submit\n• Replies to other users\' comments\n• Reactions and likes on reviews or comments\n• Photos or media attached to reviews',
      '2.4 Usage Data\n• Pages and screens you visit within the app\n• Search queries entered\n• Businesses you view, save (wishlist), or interact with\n• Time and date of your interactions\n• Device type, operating system, and app version',
      '2.5 Device & Technical Information\n• Device identifier (for push notifications)\n• IP address\n• Language and region settings\n• Crash and error reports',
      '2.6 Location Data\n• City or region used to show local businesses (only when you provide it manually through the app)',
    ],
  },
  {
    title: '3. How We Collect Your Information',
    content: [
      'We collect your information through the following means:',
      '• Directly from you when you register an account, complete your profile, or submit content within the app.',
      '• Automatically as you use the Service, through Firebase Analytics, Firebase Crashlytics, and other integrated tools.',
      '• Through Google Sign-In, if you choose to authenticate with your Google account. In that case, we receive your name, email address, and profile picture from Google as permitted by their terms.',
      '• Through push notification tokens generated by Firebase Cloud Messaging (FCM) to deliver notifications to your device.',
    ],
  },
  {
    title: '4. How We Use Your Information',
    content: [
      'We use your personal data for the following purposes:',
      '4.1 Providing and Operating the Service\n• To create and manage your account\n• To display your profile and reviews to other users\n• To allow Business Owners to manage their business listings\n• To enable you to submit, edit, and manage reviews and comments',
      '4.2 Communication\n• To send you push notifications about activity on your reviews or account (you may disable this in Settings)\n• To respond to your support tickets and customer service requests\n• To send important service announcements (e.g., policy updates)',
      '4.3 Content Moderation\n• To review user-generated content for compliance with our Community Guidelines\n• To allow administrators and moderators to manage, approve, or remove content',
      '4.4 Improving the Service\n• To analyze usage patterns and improve app features\n• To diagnose and fix technical issues using crash reports\n• To display personalized business recommendations based on your location and search history',
      '4.5 Safety and Security\n• To detect and prevent fraudulent activity, abuse, and violations of our Terms of Service\n• To verify business ownership and authenticity',
      '4.6 Legal Compliance\n• To comply with applicable Tunisian laws and regulatory requirements\n• To respond to lawful requests from public authorities',
    ],
  },
  {
    title: '5. Legal Basis for Processing',
    content: [
      'Under the Tunisian Organic Law No. 2004-63, we process your personal data on the following legal bases:',
      '• Consent: For optional data (profile picture, phone number, location) and marketing communications. You may withdraw consent at any time.',
      '• Contractual Necessity: Processing required to deliver the Service you registered for (account management, displaying reviews, business listings).',
      '• Legitimate Interest: For fraud prevention, security, and improving the Service, where these interests do not override your fundamental rights.',
      '• Legal Obligation: Where processing is required to comply with Tunisian law.',
    ],
  },
  {
    title: '6. Data Sharing and Disclosure',
    content: [
      'We do not sell, rent, or trade your personal data to third parties for commercial purposes.',
      'We may share your data in the following limited circumstances:',
      '6.1 Public Information\nYour display name, profile picture, and reviews are visible to all users of the app. Reviews linked to businesses are visible to business owners and the general public.',
      '6.2 Service Providers (Sub-processors)\nWe use the following trusted third-party services that may process your data on our behalf:\n• Google Firebase (Firestore, Authentication, Cloud Storage, Cloud Functions, Analytics, Crashlytics, FCM) — Cloud infrastructure and analytics. Our primary database is hosted in the European Union (Belgium). Some ancillary services may process data in other Google data centers.\n• Google Sign-In — Authentication provider.',
      '6.3 Legal Requirements\nWe may disclose your information when required by Tunisian law, court order, or government authority, or to protect the rights, property, or safety of TChecki, our users, or the public.',
      '6.4 Business Transfer\nIf TChecki is involved in a merger, acquisition, or sale of assets, your data may be transferred as part of that transaction. You will be notified in advance.',
    ],
  },
  {
    title: '7. International Data Transfers',
    content: [
      'TChecki uses Google Firebase, with its primary database (Firestore) hosted in the European Union (Belgium, europe-west1). Some Firebase services (Authentication, Cloud Functions, Analytics, Crashlytics) may process data on Google servers in other locations within the EU or internationally.',
      'We have chosen to host our primary database in the EU to provide a higher level of data protection, as the EU maintains strong data protection standards under the GDPR.',
      'These transfers are made subject to Google\'s standard data processing agreements and security measures, which are designed to protect your personal data to a level equivalent to or exceeding Tunisian legal requirements under Law 2004-63.',
      'In accordance with Article 27 of the Tunisian Organic Law No. 2004-63, cross-border data transfers are permitted when the receiving country ensures an adequate level of protection. The European Union is recognized as providing adequate data protection.',
      'By using the Service, you consent to the transfer and processing of your data on servers located in the European Union and, for certain ancillary services, in other jurisdictions where Google operates.',
    ],
  },
  {
    title: '8. Data Retention',
    content: [
      'We retain your personal data for as long as your account is active or as needed to provide the Service.',
      '• Account data: Retained for the lifetime of your account. Upon account deletion, your personal profile data is deleted within 30 days.',
      '• Reviews and comments: May be retained in anonymized or aggregated form even after account deletion, as they form part of the public business review record.',
      '• Support tickets: Retained for 2 years after resolution for quality assurance purposes.',
      '• Crash logs and analytics: Retained for up to 14 months.',
      'You may request deletion of your data at any time (see Section 10 — Your Rights).',
    ],
  },
  {
    title: '9. Data Security',
    content: [
      'We implement industry-standard security measures to protect your personal data:',
      '• All data transmitted between the app and our servers is encrypted using HTTPS/TLS.',
      '• Firestore security rules restrict data access so that users can only access data they are authorized to view.',
      '• Firebase Authentication provides secure identity management.',
      '• Sensitive credentials (passwords) are never stored in plain text. Firebase Authentication handles password hashing and security.',
      '• Access to personal data within our team is restricted on a need-to-know basis.',
      'Despite our efforts, no method of transmission or storage is 100% secure. We cannot guarantee absolute security, and we encourage you to use strong, unique passwords and keep them confidential.',
    ],
  },
  {
    title: '10. Your Rights',
    content: [
      'Under the Tunisian Organic Law No. 2004-63 and internationally recognized data protection principles, you have the following rights:',
      '• Right of Access: You may request a copy of the personal data we hold about you.',
      '• Right of Rectification: You may correct inaccurate or incomplete personal data through the app settings or by contacting us.',
      '• Right to Erasure: You may request deletion of your personal data. We will comply unless we are required to retain it by law or for legitimate business purposes.',
      '• Right to Object: You may object to the processing of your data for direct marketing or where processing is based on our legitimate interests.',
      '• Right to Withdraw Consent: Where processing is based on your consent, you may withdraw it at any time without affecting the lawfulness of processing prior to withdrawal.',
      '• Right to Lodge a Complaint: You have the right to lodge a complaint with the INPDP (Instance Nationale de Protection des Données Personnelles) at: www.inpdp.nat.tn',
      'To exercise any of these rights, contact us at: support@tchecki.app. We will respond within 30 days.',
    ],
  },
  {
    title: '11. Cookies and Tracking Technologies',
    content: [
      'TChecki is a mobile application and does not use browser cookies.',
      'However, we use the following tracking technologies within the app:',
      '• Firebase Analytics: Collects anonymized usage data to help us understand how users interact with the app. You may opt out by disabling notifications and analytics in your device settings.',
      '• Firebase Crashlytics: Automatically collects crash reports and error logs to help us fix bugs. Data collected is technical and does not include personally identifiable information beyond device identifiers.',
      '• Firebase Cloud Messaging (FCM): Uses a device token to deliver push notifications. You may disable push notifications in the app Settings at any time.',
    ],
  },
  {
    title: '12. Children\'s Privacy',
    content: [
      'TChecki is not intended for use by children under the age of 13.',
      'We do not knowingly collect personal data from children under 13. If you believe a child under 13 has provided us with their personal information, please contact us immediately at support@tchecki.app and we will delete that information.',
      'Users between the ages of 13 and 18 should use the Service only with the consent and supervision of a parent or legal guardian.',
    ],
  },
  {
    title: '13. Third-Party Links and Services',
    content: [
      'TChecki may display links to external websites (such as business websites, Facebook pages, or Instagram profiles). These external sites are not operated by us and have their own privacy policies.',
      'We are not responsible for the privacy practices or content of any third-party websites. We encourage you to review the privacy policies of any third-party sites you visit.',
    ],
  },
  {
    title: '14. Push Notifications',
    content: [
      'We may send you push notifications about activity relevant to your account, such as replies to your reviews or responses to your support tickets.',
      'You may control push notification preferences within the app (Settings → Notifications toggle) or through your device\'s notification settings.',
      'We will always ask for your permission before sending notifications on iOS devices.',
    ],
  },
  {
    title: '15. Changes to This Privacy Policy',
    content: [
      'We may update this Privacy Policy from time to time to reflect changes in our practices, technology, or legal requirements.',
      'When we make material changes, we will:\n• Post the updated policy within the app\n• Update the "Last Updated" date at the bottom of this document\n• Notify you via push notification or email for significant changes',
      'Your continued use of the Service after the effective date of any changes constitutes your acceptance of the updated Privacy Policy.',
      'We encourage you to review this policy periodically.',
    ],
  },
  {
    title: '16. Contact Us',
    content: [
      'If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:',
      'Email: support@tchecki.app',
      'Country: Republic of Tunisia',
      'Supervisory Authority: Instance Nationale de Protection des Données Personnelles (INPDP)\nWebsite: www.inpdp.nat.tn',
      'We are committed to resolving any concerns and will respond to all inquiries within 30 days.',
    ],
  },
];

// ── Policy content (AR) ───────────────────────────────────────────────────────
const POLICY_AR: PolicySection[] = [
  {
    title: 'مقدمة',
    content: [
      'مرحبًا بك في TChecki ("نحن" أو "لنا"). TChecki هو تطبيق جوّال مصمّم لمساعدة المستخدمين على اكتشاف الأعمال التجارية المحلية في تونس وتقييمها والتحقق منها.',
      'توضّح سياسة الخصوصية هذه كيفية جمعنا لمعلوماتك الشخصية واستخدامها وتخزينها ومشاركتها وحمايتها عند استخدامك للتطبيق.',
      'نلتزم بحماية بياناتك الشخصية وفقًا للقانون التونسي الأساسي عدد 63 لسنة 2004 المؤرخ في 27 يوليو 2004 المتعلق بحماية المعطيات الشخصية، فضلًا عن المبادئ الدولية المعترف بها في حماية البيانات.',
      'باستخدامك لـ TChecki، فإنك توافق على جمع معلوماتك واستخدامها وفق ما هو موضّح في هذه السياسة.',
    ],
  },
  {
    title: '1. من نحن',
    content: [
      'يُشغَّل TChecki ويمتلكه كيان مسجّل في الجمهورية التونسية.',
      'البلد: الجمهورية التونسية',
      'الهيئة الإشرافية: الهيئة الوطنية لحماية المعطيات الشخصية (INPDP)',
      'للتواصل بشأن أي استفسارات تتعلق بالخصوصية: support@tchecki.app',
    ],
  },
  {
    title: '2. المعلومات التي نجمعها',
    content: [
      'نجمع الفئات التالية من البيانات الشخصية:',
      '2.1 معلومات الحساب\n• الاسم الكامل\n• عنوان البريد الإلكتروني\n• رقم الهاتف (اختياري)\n• صورة الملف الشخصي (اختياري)\n• الجنس (اختياري)\n• تاريخ الميلاد (اختياري)\n• نوع الحساب (مستخدم عادي / صاحب نشاط تجاري)',
      '2.2 معلومات النشاط التجاري (لأصحاب الأعمال فقط)\n• اسم النشاط التجاري\n• التصنيف والتصنيفات الفرعية\n• الموقع / العنوان\n• الموقع الإلكتروني وروابط التواصل الاجتماعي\n• شعار النشاط وصورة الغلاف\n• وصف النشاط التجاري',
      '2.3 المحتوى الذي يُنشئه المستخدم\n• التقييمات والمراجعات والتعليقات\n• الردود على تعليقات المستخدمين الآخرين\n• الإعجابات والتفاعلات\n• الصور المرفقة بالمراجعات',
      '2.4 بيانات الاستخدام\n• الشاشات والصفحات التي تزورها\n• استعلامات البحث\n• الأعمال التجارية التي تشاهدها أو تحفظها\n• التاريخ والوقت للتفاعلات',
      '2.5 بيانات الجهاز والمعلومات التقنية\n• معرّف الجهاز (للإشعارات)\n• عنوان IP\n• إعدادات اللغة والمنطقة\n• تقارير الأعطال والأخطاء',
      '2.6 بيانات الموقع\n• المدينة أو المنطقة التي تُدخلها يدويًا لعرض الأعمال المحلية القريبة',
    ],
  },
  {
    title: '3. كيف نجمع معلوماتك',
    content: [
      'نجمع معلوماتك من خلال:',
      '• مباشرةً منك عند تسجيل الحساب أو إكمال ملفك الشخصي أو إرسال محتوى داخل التطبيق.',
      '• تلقائيًا أثناء استخدامك للخدمة عبر Firebase Analytics وFirebase Crashlytics.',
      '• من خلال تسجيل الدخول بـ Google إذا اخترت ذلك، وفي هذه الحالة نتلقى اسمك وبريدك الإلكتروني وصورتك الشخصية من Google.',
      '• عبر رموز الإشعارات التي يُنشئها Firebase Cloud Messaging (FCM).',
    ],
  },
  {
    title: '4. كيف نستخدم معلوماتك',
    content: [
      'نستخدم بياناتك الشخصية للأغراض التالية:',
      '4.1 تقديم الخدمة وتشغيلها\n• إنشاء حسابك وإدارته\n• عرض ملفك الشخصي ومراجعاتك\n• السماح لأصحاب الأعمال بإدارة قوائمهم\n• تمكينك من تقديم المراجعات والتعليقات وإدارتها',
      '4.2 التواصل\n• إرسال إشعارات فورية حول النشاط المتعلق بحسابك\n• الرد على طلبات الدعم\n• إرسال إشعارات هامة بشأن الخدمة',
      '4.3 إشراف المحتوى\n• مراجعة المحتوى للتحقق من مطابقته لإرشادات المجتمع\n• إدارة المحتوى من قِبل المسؤولين والمشرفين',
      '4.4 تحسين الخدمة\n• تحليل أنماط الاستخدام لتطوير ميزات التطبيق\n• تشخيص المشاكل التقنية\n• عرض توصيات مخصصة بناءً على موقعك واهتماماتك',
      '4.5 الأمان والسلامة\n• الكشف عن الاحتيال والانتهاكات ومنعها\n• التحقق من ملكية الأعمال التجارية',
      '4.6 الامتثال القانوني\n• الامتثال للقوانين التونسية المعمول بها\n• الاستجابة للطلبات القانونية الصادرة عن السلطات المختصة',
    ],
  },
  {
    title: '5. الأساس القانوني للمعالجة',
    content: [
      'بموجب القانون التونسي الأساسي عدد 63 لسنة 2004، نعالج بياناتك الشخصية على الأسس القانونية التالية:',
      '• الموافقة: للبيانات الاختيارية والاتصالات التسويقية. يمكنك سحب موافقتك في أي وقت.',
      '• الضرورة التعاقدية: لتقديم الخدمة التي اشتركت فيها.',
      '• المصلحة المشروعة: لمنع الاحتيال والأمان وتحسين الخدمة.',
      '• الالتزام القانوني: عند الاقتضاء بموجب القانون التونسي.',
    ],
  },
  {
    title: '6. مشاركة البيانات والإفصاح عنها',
    content: [
      'لا نبيع بياناتك الشخصية ولا نؤجّرها ولا نتاجر بها مع أطراف ثالثة لأغراض تجارية.',
      'قد نشارك بياناتك في الحالات المحدودة التالية:',
      '6.1 المعلومات العامة\nاسمك وصورتك الشخصية ومراجعاتك مرئية لجميع مستخدمي التطبيق. المراجعات المرتبطة بالأعمال مرئية لأصحابها وللعامة.',
      '6.2 مزوّدو الخدمة\nنستخدم خدمات Google Firebase (Firestore، Authentication، Cloud Storage، Functions، Analytics، Crashlytics، FCM) كبنية تحتية سحابية. تُستضاف قاعدة بياناتنا الرئيسية في الاتحاد الأوروبي (بلجيكا). قد تعالج بعض الخدمات المساعدة البيانات في مراكز بيانات Google الأخرى.',
      '6.3 المتطلبات القانونية\nقد نكشف عن معلوماتك عند الاقتضاء بموجب القانون التونسي أو أمر قضائي أو سلطة حكومية.',
      '6.4 نقل الأعمال\nإذا انخرطت TChecki في عملية دمج أو استحواذ أو بيع أصول، فقد تُنقل بياناتك. سيتم إخطارك مسبقًا.',
    ],
  },
  {
    title: '7. النقل الدولي للبيانات',
    content: [
      'يستخدم TChecki خدمة Google Firebase، حيث تُستضاف قاعدة البيانات الرئيسية (Firestore) في الاتحاد الأوروبي (بلجيكا، europe-west1). قد تعالج بعض خدمات Firebase الأخرى (المصادقة، الوظائف السحابية، التحليلات، تقارير الأعطال) البيانات على خوادم Google في مواقع أخرى داخل الاتحاد الأوروبي أو دوليًا.',
      'اخترنا استضافة قاعدة بياناتنا الرئيسية في الاتحاد الأوروبي لتوفير مستوى أعلى من حماية البيانات، إذ يحافظ الاتحاد الأوروبي على معايير قوية لحماية البيانات بموجب اللائحة العامة لحماية البيانات (GDPR).',
      'تتم هذه النقلات وفقًا لاتفاقيات معالجة البيانات القياسية لـ Google وتدابير الأمان المصممة لحماية بياناتك بمستوى يعادل أو يفوق المتطلبات القانونية التونسية بموجب القانون عدد 63 لسنة 2004.',
      'وفقًا للفصل 27 من القانون الأساسي التونسي عدد 63 لسنة 2004، يُسمح بنقل البيانات عبر الحدود عندما يضمن البلد المستقبل مستوى حماية كافيًا. يُعترف بالاتحاد الأوروبي كمنطقة توفر حماية كافية للبيانات.',
      'باستخدامك للخدمة، فإنك توافق على نقل بياناتك ومعالجتها على خوادم في الاتحاد الأوروبي، ولبعض الخدمات المساعدة، في مواقع أخرى تعمل فيها Google.',
    ],
  },
  {
    title: '8. الاحتفاظ بالبيانات',
    content: [
      'نحتفظ ببياناتك الشخصية طالما أن حسابك نشط أو طالما دعت الحاجة إلى ذلك لتوفير الخدمة.',
      '• بيانات الحساب: تُحتفظ طوال حياة حسابك. عند حذف الحساب، تُحذف بيانات الملف الشخصي خلال 30 يومًا.',
      '• المراجعات والتعليقات: قد تُحتفظ في شكل مُجهَّل أو مجمَّع بعد حذف الحساب.',
      '• تذاكر الدعم: تُحتفظ لمدة سنتين بعد الحل.',
      '• سجلات الأعطال والتحليلات: تُحتفظ لمدة 14 شهرًا.',
    ],
  },
  {
    title: '9. أمان البيانات',
    content: [
      'نطبّق تدابير أمنية وفق معايير الصناعة لحماية بياناتك الشخصية:',
      '• جميع البيانات المنقولة بين التطبيق وخوادمنا مُشفَّرة باستخدام HTTPS/TLS.',
      '• تحدّ قواعد أمان Firestore الوصول إلى البيانات للمستخدمين المصرّح لهم فقط.',
      '• يوفر Firebase Authentication إدارة هوية آمنة.',
      '• لا تُخزَّن كلمات المرور بنص عادي أبدًا — يتولى Firebase Authentication تشفيرها.',
      '• الوصول إلى البيانات الشخصية داخل فريقنا مقيَّد بمبدأ الحاجة إلى المعرفة.',
      'رغم جهودنا، لا يوجد وسيلة نقل أو تخزين آمنة بنسبة 100%. نشجّعك على استخدام كلمات مرور قوية وفريدة.',
    ],
  },
  {
    title: '10. حقوقك',
    content: [
      'بموجب القانون التونسي الأساسي عدد 63 لسنة 2004 والمبادئ الدولية لحماية البيانات، تتمتع بالحقوق التالية:',
      '• حق الوصول: يمكنك طلب نسخة من بياناتك الشخصية التي نحتفظ بها.',
      '• حق التصحيح: يمكنك تصحيح البيانات الشخصية غير الدقيقة أو غير المكتملة عبر إعدادات التطبيق.',
      '• حق الحذف: يمكنك طلب حذف بياناتك الشخصية ما لم يكن القانون يُلزمنا بالاحتفاظ بها.',
      '• حق الاعتراض: يمكنك الاعتراض على معالجة بياناتك لأغراض التسويق المباشر.',
      '• حق سحب الموافقة: يمكنك سحب موافقتك في أي وقت دون المساس بمشروعية المعالجة السابقة.',
      '• حق تقديم شكوى: يحق لك تقديم شكوى إلى INPDP على الموقع: www.inpdp.nat.tn',
      'لممارسة أي من هذه الحقوق، تواصل معنا على: support@tchecki.app. سنردّ خلال 30 يومًا.',
    ],
  },
  {
    title: '11. ملفات تعريف الارتباط وتقنيات التتبع',
    content: [
      'TChecki تطبيق جوّال ولا يستخدم ملفات تعريف الارتباط في المتصفح.',
      'لكننا نستخدم تقنيات التتبع التالية داخل التطبيق:',
      '• Firebase Analytics: يجمع بيانات استخدام مجهولة. يمكنك إلغاء الاشتراك عبر إعدادات الجهاز.',
      '• Firebase Crashlytics: يجمع تلقائيًا تقارير الأعطال وسجلات الأخطاء. البيانات تقنية فقط.',
      '• Firebase Cloud Messaging (FCM): يستخدم رمز الجهاز لتسليم الإشعارات الفورية. يمكنك تعطيل الإشعارات في إعدادات التطبيق.',
    ],
  },
  {
    title: '12. خصوصية الأطفال',
    content: [
      'TChecki غير مخصص للأطفال دون سن 13 عامًا.',
      'لا نجمع عمدًا بيانات شخصية من الأطفال دون 13 عامًا. إذا اعتقدت أن طفلًا دون 13 عامًا قدّم لنا معلوماته، يُرجى التواصل معنا فورًا على support@tchecki.app.',
      'يجب على المستخدمين بين 13 و18 عامًا استخدام الخدمة بإشراف وموافقة ولي الأمر.',
    ],
  },
  {
    title: '13. روابط وخدمات الأطراف الثالثة',
    content: [
      'قد يعرض TChecki روابط لمواقع خارجية (مواقع الأعمال، صفحات Facebook، Instagram). هذه المواقع لا تُديرها TChecki ولها سياسات خصوصية خاصة بها.',
      'لسنا مسؤولين عن ممارسات الخصوصية أو محتوى أي مواقع خارجية. ننصحك بمراجعة سياسات خصوصية المواقع الخارجية التي تزورها.',
    ],
  },
  {
    title: '14. الإشعارات الفورية',
    content: [
      'قد نرسل إليك إشعارات فورية حول النشاط المتعلق بحسابك، كالردود على مراجعاتك أو تذاكر الدعم.',
      'يمكنك التحكم في تفضيلات الإشعارات داخل التطبيق (الإعدادات ← تبديل الإشعارات) أو من خلال إعدادات الجهاز.',
    ],
  },
  {
    title: '15. التغييرات على سياسة الخصوصية هذه',
    content: [
      'قد نُحدّث سياسة الخصوصية هذه من وقت لآخر.',
      'عند إجراء تغييرات جوهرية، سنقوم بـ:\n• نشر السياسة المُحدَّثة داخل التطبيق\n• تحديث تاريخ "آخر تحديث" في أسفل هذه الوثيقة\n• إرسال إشعار فوري أو بريد إلكتروني للتغييرات الكبرى',
      'يُعدّ استمرارك في استخدام الخدمة بعد سريان أي تغييرات قبولًا لسياسة الخصوصية المُحدَّثة.',
    ],
  },
  {
    title: '16. تواصل معنا',
    content: [
      'إذا كانت لديك أي أسئلة أو مخاوف أو طلبات تتعلق بسياسة الخصوصية هذه، يُرجى التواصل معنا:',
      'البريد الإلكتروني: support@tchecki.app',
      'البلد: الجمهورية التونسية',
      'الهيئة الإشرافية: الهيئة الوطنية لحماية المعطيات الشخصية (INPDP)\nالموقع: www.inpdp.nat.tn',
      'سنردّ على جميع الاستفسارات خلال 30 يومًا.',
    ],
  },
];

// ── Sub-components ─────────────────────────────────────────────────────────────
interface SectionProps {
  section: PolicySection;
  theme: ReturnType<typeof useTheme>;
  isRTL: boolean;
}

const PolicySectionCard = React.memo(({ section, theme, isRTL }: SectionProps) => (
  <View
    style={{
      backgroundColor: theme.card,
      borderRadius: 14,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.border,
    }}
  >
    <AppText
      style={{
        fontSize: 15,
        fontWeight: '700',
        color: colors.neonPurple,
        marginBottom: 10,
        textAlign: isRTL ? 'right' : 'left',
      }}
    >
      {section.title}
    </AppText>
    {section.content.map((paragraph, idx) => (
      <AppText
        key={idx}
        style={{
          fontSize: 13,
          color: theme.textSecondary,
          lineHeight: 20,
          marginTop: idx > 0 ? 8 : 0,
          textAlign: isRTL ? 'right' : 'left',
        }}
      >
        {paragraph}
      </AppText>
    ))}
  </View>
));

// ── Main Screen ────────────────────────────────────────────────────────────────
export default function PrivacyPolicyScreen() {
  const { t, i18n } = useTranslation();
  const router = useRouter();
  const theme = useTheme();
  const isRTL = i18n.language === 'ar';
  const sections = isRTL ? POLICY_AR : POLICY_EN;

  return (
    <ScreenLayout>
      {/* Header */}
      <View
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          gap: 12,
          paddingHorizontal: 16,
          paddingTop: 8,
          paddingBottom: 16,
          borderBottomWidth: 1,
          borderBottomColor: theme.border,
        }}
      >
        <Pressable
          onPress={() => router.back()}
          accessibilityRole="button"
          accessibilityLabel={t('common.back')}
        >
          <MaterialCommunityIcons
            name={isRTL ? 'arrow-right' : 'arrow-left'}
            size={24}
            color={theme.text}
          />
        </Pressable>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1 }}>
          <MaterialCommunityIcons name="shield-outline" size={22} color={colors.neonPurple} />
          <AppText style={{ fontSize: 17, fontWeight: '600', color: theme.text }}>
            {t('settings.privacyPolicy')}
          </AppText>
        </View>
      </View>

      <ScrollView
        style={{ flex: 1 }}
        contentContainerStyle={{ paddingHorizontal: 16, paddingTop: 16, paddingBottom: 40, gap: 10 }}
        showsVerticalScrollIndicator={false}
      >
        {/* Effective date banner */}
        <View
          style={{
            backgroundColor: `${colors.neonPurple}15`,
            borderRadius: 12,
            padding: 14,
            flexDirection: 'row',
            gap: 10,
            borderWidth: 1,
            borderColor: `${colors.neonPurple}30`,
            marginBottom: 4,
          }}
        >
          <MaterialCommunityIcons
            name="calendar-check-outline"
            size={18}
            color={colors.neonPurple}
            style={{ marginTop: 1 }}
          />
          <AppText style={{ flex: 1, fontSize: 12, color: theme.textSecondary, lineHeight: 18 }}>
            {isRTL
              ? 'آخر تحديث: 22 مارس 2026 — تسري هذه السياسة على جميع مستخدمي تطبيق TChecki في تونس.'
              : 'Last Updated: March 22, 2026 — This policy applies to all users of TChecki in Tunisia.'}
          </AppText>
        </View>

        {sections.map((section, idx) => (
          <PolicySectionCard key={idx} section={section} theme={theme} isRTL={isRTL} />
        ))}

        {/* Footer */}
        <View style={{ alignItems: 'center', paddingTop: 8 }}>
          <AppText style={{ fontSize: 11, color: theme.textSecondary, textAlign: 'center' }}>
            {isRTL
              ? '© 2026 TChecki. جميع الحقوق محفوظة. الجمهورية التونسية.'
              : '© 2026 TChecki. All rights reserved. Republic of Tunisia.'}
          </AppText>
        </View>
      </ScrollView>
    </ScreenLayout>
  );
}
