/**
 * Firestore Seed Script
 *
 * Seeds the Firestore database with the canonical categories (incl. subcategories
 * and rating criteria) and sample businesses.
 *
 * Usage:
 *   npx ts-node scripts/seed-firestore.ts
 *
 * Or via Firebase emulator:
 *   Set FIRESTORE_EMULATOR_HOST=localhost:8080 before running
 */

import { initializeApp } from 'firebase/app';
import {
  getFirestore,
  collection,
  doc,
  setDoc,
  serverTimestamp,
} from 'firebase/firestore';
import { CATEGORIES_DATA } from '../src/core/constants/categoriesData';

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY || 'AIzaSyC2P11O4HM--Gu8XaCV3lRgg-hqZ7qvV8g',
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || 'reviewhub-91cfb.firebaseapp.com',
  projectId: process.env.FIREBASE_PROJECT_ID || 'reviewhub-91cfb',
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || 'reviewhub-91cfb.firebasestorage.app',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '713435343120',
  appId: process.env.FIREBASE_APP_ID || '1:713435343120:web:054ce9a892746b748cdd95',
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// ── Sample Businesses ───────────────────────────────────────────────────────

const BUSINESSES = [
  {
    id: 'restaurant_el_ali',
    name: 'Restaurant El Ali',
    description: 'Traditional Tunisian cuisine in the heart of the Medina. Savoury couscous, slow-cooked lamb tagines and house-made brik make this a local favourite for generations.',
    category_id: 'restaurant',
    category_name: 'Restaurant',
    subcategory_id: 'tunisian',
    subcategory_name: 'Tunisian',
    location: 'Medina, Tunis',
    latitude: 36.7992,
    longitude: 10.1685,
    cover_image_url: 'https://picsum.photos/seed/elali-cover/800/400',
    logo_url: 'https://picsum.photos/seed/elali-logo/200/200',
    rating: 4.5,
    review_count: 535,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 71 000 001',
      email: 'info@elali.tn',
      website: 'https://elali.tn',
      instagram_handle: null,
      facebook_name: 'RestaurantElAli',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [
      { id: 'starters', name: 'Starters & Brik', items: [] },
      { id: 'soups', name: 'Soups', items: [] },
      { id: 'couscous', name: 'Couscous', items: [] },
      { id: 'tagines', name: 'Tagines', items: [] },
      { id: 'desserts', name: 'Desserts', items: [] },
    ],
    rating_distribution: [
      { stars: 5, percentage: 52 },
      { stars: 4, percentage: 28 },
      { stars: 3, percentage: 11 },
      { stars: 2, percentage: 6 },
      { stars: 1, percentage: 3 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.5 },
      { name: 'Food Quality', icon: 'silverware-fork-knife', rating: 4.6 },
      { name: 'Cleanliness', icon: 'broom', rating: 4.3 },
    ],
  },
  {
    id: 'le_golfe',
    name: 'Le Golfe',
    description: 'Premium seafood restaurant with Mediterranean views. Fresh fish, grilled lobster and a fine wine selection make Le Golfe the destination for special occasions by the sea.',
    category_id: 'restaurant',
    category_name: 'Restaurant',
    subcategory_id: 'french',
    subcategory_name: 'French',
    location: 'La Marsa, Tunis',
    latitude: 36.8784,
    longitude: 10.3234,
    cover_image_url: 'https://picsum.photos/seed/legolfe-cover/800/400',
    logo_url: 'https://picsum.photos/seed/legolfe-logo/200/200',
    rating: 4.3,
    review_count: 310,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 71 000 002',
      email: 'contact@legolfe.tn',
      website: null,
      instagram_handle: 'legolfe_tn',
      facebook_name: null,
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [
      { id: 'starters', name: 'Starters', items: [] },
      { id: 'seafood', name: 'Seafood', items: [] },
      { id: 'grills', name: 'Grills', items: [] },
      { id: 'desserts', name: 'Desserts', items: [] },
      { id: 'wines', name: 'Wines & Beverages', items: [] },
    ],
    rating_distribution: [
      { stars: 5, percentage: 48 },
      { stars: 4, percentage: 32 },
      { stars: 3, percentage: 13 },
      { stars: 2, percentage: 5 },
      { stars: 1, percentage: 2 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.3 },
      { name: 'Food Quality', icon: 'silverware-fork-knife', rating: 4.4 },
      { name: 'Cleanliness', icon: 'broom', rating: 4.2 },
    ],
  },
  {
    id: 'dar_el_jeld',
    name: 'Dar El Jeld',
    description: 'Fine dining in a restored 18th-century palace. Dar El Jeld offers an unmatched combination of authentic Tunisian haute cuisine and breathtaking Andalusian courtyard ambiance.',
    category_id: 'restaurant',
    category_name: 'Restaurant',
    subcategory_id: 'tunisian',
    subcategory_name: 'Tunisian',
    location: 'Medina, Tunis',
    latitude: 36.7981,
    longitude: 10.1695,
    cover_image_url: 'https://picsum.photos/seed/dareljeld-cover/800/400',
    logo_url: 'https://picsum.photos/seed/dareljeld-logo/200/200',
    rating: 4.7,
    review_count: 620,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 71 000 003',
      email: 'reservations@dareljeld.tn',
      website: null,
      instagram_handle: 'dareljeld',
      facebook_name: 'DarElJeld',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [
      { id: 'starters', name: 'Starters & Salads', items: [] },
      { id: 'soups', name: 'Soups', items: [] },
      { id: 'couscous', name: 'Couscous', items: [] },
      { id: 'tagines', name: 'Tagines', items: [] },
      { id: 'grills', name: 'Grills', items: [] },
      { id: 'desserts', name: 'Desserts', items: [] },
    ],
    rating_distribution: [
      { stars: 5, percentage: 62 },
      { stars: 4, percentage: 24 },
      { stars: 3, percentage: 8 },
      { stars: 2, percentage: 4 },
      { stars: 1, percentage: 2 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.6 },
      { name: 'Food Quality', icon: 'silverware-fork-knife', rating: 4.8 },
      { name: 'Cleanliness', icon: 'broom', rating: 4.7 },
    ],
  },
  {
    id: 'fit_zone',
    name: 'Fit Zone',
    description: 'Modern gym with state-of-the-art equipment, professional trainers and a full range of classes including HIIT, yoga, and spin. Open 7 days a week.',
    category_id: 'gym',
    category_name: 'Gym',
    subcategory_id: 'fitness_gym',
    subcategory_name: 'Fitness Gym',
    location: 'Lac 2, Tunis',
    latitude: 36.8390,
    longitude: 10.2306,
    cover_image_url: 'https://picsum.photos/seed/fitzone-cover/800/400',
    logo_url: 'https://picsum.photos/seed/fitzone-logo/200/200',
    rating: 4.2,
    review_count: 180,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 71 000 004',
      email: 'hello@fitzone.tn',
      website: null,
      instagram_handle: 'fitzone_tn',
      facebook_name: 'FitZoneTunis',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 44 },
      { stars: 4, percentage: 33 },
      { stars: 3, percentage: 14 },
      { stars: 2, percentage: 6 },
      { stars: 1, percentage: 3 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.2 },
      { name: 'Equipment Quality', icon: 'dumbbell', rating: 4.3 },
      { name: 'Cleanliness', icon: 'broom', rating: 4.1 },
    ],
  },
  {
    id: 'cafe_des_nattes',
    name: 'Café des Nattes',
    description: 'The most iconic café in Sidi Bou Said, perched above the village square since the 19th century. Sip mint tea and smoke a chicha while enjoying the timeless blue-and-white view.',
    category_id: 'coffee_shop',
    category_name: 'Coffee Shop',
    subcategory_id: null,
    subcategory_name: null,
    location: 'Sidi Bou Said, Tunis',
    latitude: 36.8695,
    longitude: 10.3416,
    cover_image_url: 'https://picsum.photos/seed/cafedesnattes-cover/800/400',
    logo_url: 'https://picsum.photos/seed/cafedesnattes-logo/200/200',
    rating: 4.6,
    review_count: 890,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 71 000 005',
      email: null,
      website: null,
      instagram_handle: null,
      facebook_name: 'CafeDesNattes',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [
      { id: 'hot_drinks', name: 'Hot Drinks', items: [] },
      { id: 'cold_drinks', name: 'Cold Drinks', items: [] },
      { id: 'pastries', name: 'Pastries & Sweets', items: [] },
    ],
    rating_distribution: [
      { stars: 5, percentage: 56 },
      { stars: 4, percentage: 28 },
      { stars: 3, percentage: 9 },
      { stars: 2, percentage: 5 },
      { stars: 1, percentage: 2 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.4 },
      { name: 'Product Quality', icon: 'star-check', rating: 4.7 },
      { name: 'Cleanliness', icon: 'broom', rating: 4.6 },
    ],
  },
  {
    id: 'restaurant_dar_zarrouk',
    name: 'Dar Zarrouk',
    description: 'An iconic fine-dining Tunisian restaurant perched on the cliffside of Sidi Bou Said, offering breathtaking sea views and an extensive menu of authentic Tunisian dishes — from smoky brik pastries and spiced merguez to slow-cooked lamb tagine and traditional couscous.',
    category_id: 'restaurant',
    category_name: 'Restaurant',
    subcategory_id: 'tunisian',
    subcategory_name: 'Tunisian',
    location: 'Sidi Bou Said, Tunis',
    latitude: 36.8703,
    longitude: 10.3421,
    cover_image_url: 'https://picsum.photos/seed/darzarrouk-cover/800/400',
    logo_url: 'https://picsum.photos/seed/darzarrouk-logo/200/200',
    rating: 4.6,
    review_count: 748,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 71 740 591',
      email: 'reservations@darzarrouk.tn',
      website: 'https://darzarrouk.tn',
      instagram_handle: 'darzarrouk',
      facebook_name: 'DarZarrouk',
      tiktok_handle: null,
    },
    delivery_services: [
      { id: 'glovo', name: 'Glovo', abbreviation: 'GLV', is_active: true, url: 'https://glovoapp.com' },
      { id: 'jumia_food', name: 'Jumia Food', abbreviation: 'JMF', is_active: true, url: null },
    ],
    menu_categories: [
      { id: 'starters', name: 'Starters & Brik', items: [] },
      { id: 'soups', name: 'Soups', items: [] },
      { id: 'salads', name: 'Salads', items: [] },
      { id: 'couscous', name: 'Couscous', items: [] },
      { id: 'tagines', name: 'Tagines', items: [] },
      { id: 'grills', name: 'Grills & Mechoui', items: [] },
      { id: 'seafood', name: 'Seafood', items: [] },
      { id: 'desserts', name: 'Desserts', items: [] },
      { id: 'beverages', name: 'Beverages', items: [] },
    ],
    rating_distribution: [
      { stars: 5, percentage: 56 },
      { stars: 4, percentage: 28 },
      { stars: 3, percentage: 10 },
      { stars: 2, percentage: 4 },
      { stars: 1, percentage: 2 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.5 },
      { name: 'Food Quality', icon: 'silverware-fork-knife', rating: 4.7 },
      { name: 'Cleanliness', icon: 'broom', rating: 4.6 },
    ],
  },
  {
    id: 'hotel_the_residence',
    name: 'The Residence Tunis',
    description: 'Luxury beachfront resort in Gammarth offering world-class spa, four restaurants, a private beach and panoramic views of the Mediterranean. A five-star retreat steps from the capital.',
    category_id: 'hebergement',
    category_name: 'Hebergement',
    subcategory_id: 'hotel',
    subcategory_name: 'Hotel',
    location: 'Gammarth, Tunis',
    latitude: 36.9118,
    longitude: 10.2923,
    cover_image_url: 'https://picsum.photos/seed/theresidence-cover/800/400',
    logo_url: 'https://picsum.photos/seed/theresidence-logo/200/200',
    rating: 4.8,
    review_count: 1250,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 71 000 006',
      email: 'info@theresidence.tn',
      website: 'https://theresidence.tn',
      instagram_handle: 'theresidencetunis',
      facebook_name: 'TheResidenceTunis',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 64 },
      { stars: 4, percentage: 24 },
      { stars: 3, percentage: 8 },
      { stars: 2, percentage: 2 },
      { stars: 1, percentage: 2 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.7 },
      { name: 'Location', icon: 'map-marker', rating: 4.9 },
      { name: 'Cleanliness', icon: 'broom', rating: 4.8 },
    ],
  },

  // ── Delivery Companies in Tunisia ─────────────────────────────────────────

  {
    id: 'delivery_first_delivery',
    name: 'First Delivery',
    description: 'The most popular delivery company in Tunisia, founded in 2018 by Marouane Ratel. A 100% Tunisian company with a fleet of over 450 vehicles and 14 agencies across Tunisia, offering express parcel delivery, cash-on-delivery collection, and real-time tracking.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'parcel_delivery',
    subcategory_name: 'Parcel Delivery',
    location: 'Charguia 1, La Soukra, Tunis',
    latitude: 36.8356,
    longitude: 10.1986,
    cover_image_url: 'https://picsum.photos/seed/firstdelivery-cover/800/400',
    logo_url: 'https://picsum.photos/seed/firstdelivery-logo/200/200',
    rating: 4.3,
    review_count: 1250,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 36 010 550',
      email: 'info@firstdeliverygroup.com',
      website: 'https://www.firstdeliverygroup.com',
      instagram_handle: null,
      facebook_name: 'first.delivery.group',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 45 },
      { stars: 4, percentage: 30 },
      { stars: 3, percentage: 14 },
      { stars: 2, percentage: 7 },
      { stars: 1, percentage: 4 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.3 },
      { name: 'Promptness', icon: 'clock-fast', rating: 4.2 },
    ],
  },
  {
    id: 'delivery_adex',
    name: 'Adex',
    description: 'Tunisian delivery company based in Sfax offering fast and secure parcel delivery across all of Tunisia. Known for real-time package tracking, customer satisfaction focus, and coverage of all 24 governorates.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'parcel_delivery',
    subcategory_name: 'Parcel Delivery',
    location: 'Route l\'Afrane km3, Sfax',
    latitude: 34.7406,
    longitude: 10.7603,
    cover_image_url: 'https://picsum.photos/seed/adex-cover/800/400',
    logo_url: 'https://picsum.photos/seed/adex-logo/200/200',
    rating: 4.1,
    review_count: 680,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 55 781 000',
      email: 'contact@adex.tn',
      website: 'https://adex.tn',
      instagram_handle: 'adex.tunisie',
      facebook_name: 'AdEx.tn',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 40 },
      { stars: 4, percentage: 32 },
      { stars: 3, percentage: 16 },
      { stars: 2, percentage: 8 },
      { stars: 1, percentage: 4 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.1 },
      { name: 'Promptness', icon: 'clock-fast', rating: 4.0 },
    ],
  },
  {
    id: 'delivery_navex',
    name: 'Navex Delivery',
    description: 'Founded in 2021, Navex Delivery offers fast, reliable and transparent delivery services throughout Tunisia within 24 hours. Known for transparent pricing, parcel security, and serving both businesses and individuals.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'parcel_delivery',
    subcategory_name: 'Parcel Delivery',
    location: 'Charguia 1, Tunis',
    latitude: 36.8340,
    longitude: 10.1975,
    cover_image_url: 'https://picsum.photos/seed/navex-cover/800/400',
    logo_url: 'https://picsum.photos/seed/navex-logo/200/200',
    rating: 4.2,
    review_count: 520,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 21 079 000',
      email: null,
      website: 'https://navex.tn',
      instagram_handle: null,
      facebook_name: 'navex.delivery',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 42 },
      { stars: 4, percentage: 31 },
      { stars: 3, percentage: 15 },
      { stars: 2, percentage: 8 },
      { stars: 1, percentage: 4 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.2 },
      { name: 'Promptness', icon: 'clock-fast', rating: 4.3 },
    ],
  },
  {
    id: 'delivery_best_delivery',
    name: 'Best Delivery',
    description: 'Founded in 2019, Best Delivery specializes in road transport and parcel delivery across Tunisia. Offers additional services including cash-on-delivery (COD) refunds and storage solutions. Covers Ben Arous, Gafsa, Medenine, Tunis, Sfax, and Sousse.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'parcel_delivery',
    subcategory_name: 'Parcel Delivery',
    location: 'Ben Arous, Tunis',
    latitude: 36.7533,
    longitude: 10.2283,
    cover_image_url: 'https://picsum.photos/seed/bestdelivery-cover/800/400',
    logo_url: 'https://picsum.photos/seed/bestdelivery-logo/200/200',
    rating: 4.0,
    review_count: 340,
    is_featured: false,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 29 921 692',
      email: 'best@best-delivery.net',
      website: 'https://best-delivery.net',
      instagram_handle: null,
      facebook_name: null,
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 38 },
      { stars: 4, percentage: 30 },
      { stars: 3, percentage: 18 },
      { stars: 2, percentage: 9 },
      { stars: 1, percentage: 5 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.0 },
      { name: 'Promptness', icon: 'clock-fast', rating: 3.9 },
    ],
  },
  {
    id: 'delivery_mylerz',
    name: 'Mylerz',
    description: 'International end-to-end logistics company operating across Tunisia, Egypt, Morocco, Jordan, and Algeria. Services include domestic last-mile delivery, cross-border e-commerce solutions, international express shipping, fulfillment, and heavyweight delivery.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'parcel_delivery',
    subcategory_name: 'Parcel Delivery',
    location: 'Charguia 2, Tunis',
    latitude: 36.8380,
    longitude: 10.2050,
    cover_image_url: 'https://picsum.photos/seed/mylerz-cover/800/400',
    logo_url: 'https://picsum.photos/seed/mylerz-logo/200/200',
    rating: 4.1,
    review_count: 290,
    is_featured: false,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 31 226 666',
      email: 'contact.tunisie@mylerz.com',
      website: 'https://www.mylerz.com',
      instagram_handle: null,
      facebook_name: 'mylerz.tunisia',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 39 },
      { stars: 4, percentage: 31 },
      { stars: 3, percentage: 17 },
      { stars: 2, percentage: 8 },
      { stars: 1, percentage: 5 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.1 },
      { name: 'Promptness', icon: 'clock-fast', rating: 4.0 },
    ],
  },
  {
    id: 'delivery_droppex',
    name: 'Droppex',
    description: 'Tunisian delivery and e-commerce solutions company based in Sousse. Provides rapid delivery with national and international coverage, COD services, and integrated e-commerce logistics solutions for online sellers.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'parcel_delivery',
    subcategory_name: 'Parcel Delivery',
    location: 'Sousse, Tunisia',
    latitude: 35.8256,
    longitude: 10.6369,
    cover_image_url: 'https://picsum.photos/seed/droppex-cover/800/400',
    logo_url: 'https://picsum.photos/seed/droppex-logo/200/200',
    rating: 3.9,
    review_count: 210,
    is_featured: false,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: null,
      email: null,
      website: 'https://www.droppex.com',
      instagram_handle: null,
      facebook_name: 'droppex.tunisie',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 35 },
      { stars: 4, percentage: 30 },
      { stars: 3, percentage: 19 },
      { stars: 2, percentage: 10 },
      { stars: 1, percentage: 6 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 3.9 },
      { name: 'Promptness', icon: 'clock-fast', rating: 3.8 },
    ],
  },
  {
    id: 'delivery_jetpack',
    name: 'Jetpack',
    description: 'Tunisian delivery company offering pick-up and delivery services with cash-on-delivery payment options. Focused on e-commerce logistics with fast processing and reliable parcel handling across Tunisia.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'parcel_delivery',
    subcategory_name: 'Parcel Delivery',
    location: 'Tunis, Tunisia',
    latitude: 36.8065,
    longitude: 10.1815,
    cover_image_url: 'https://picsum.photos/seed/jetpack-cover/800/400',
    logo_url: 'https://picsum.photos/seed/jetpack-logo/200/200',
    rating: 3.8,
    review_count: 150,
    is_featured: false,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: null,
      email: null,
      website: null,
      instagram_handle: null,
      facebook_name: null,
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 33 },
      { stars: 4, percentage: 29 },
      { stars: 3, percentage: 20 },
      { stars: 2, percentage: 11 },
      { stars: 1, percentage: 7 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 3.8 },
      { name: 'Promptness', icon: 'clock-fast', rating: 3.7 },
    ],
  },
  {
    id: 'delivery_bestway',
    name: 'Bestway',
    description: 'Local Tunisian delivery service offering parcel delivery and logistics solutions. Part of the growing e-commerce delivery ecosystem in Tunisia with coverage across major cities.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'parcel_delivery',
    subcategory_name: 'Parcel Delivery',
    location: 'Tunis, Tunisia',
    latitude: 36.8100,
    longitude: 10.1660,
    cover_image_url: 'https://picsum.photos/seed/bestway-cover/800/400',
    logo_url: 'https://picsum.photos/seed/bestway-logo/200/200',
    rating: 3.7,
    review_count: 120,
    is_featured: false,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: null,
      email: null,
      website: null,
      instagram_handle: null,
      facebook_name: null,
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 30 },
      { stars: 4, percentage: 28 },
      { stars: 3, percentage: 22 },
      { stars: 2, percentage: 12 },
      { stars: 1, percentage: 8 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 3.7 },
      { name: 'Promptness', icon: 'clock-fast', rating: 3.6 },
    ],
  },
  {
    id: 'delivery_tunisia_express',
    name: 'Tunisia Express',
    description: 'Founded in 2006, Tunisia Express specializes in international transport, logistics, courier, and parcel delivery. Covers 100% of Tunisian territory through 12 agencies across 6 governorates. One of the oldest and most established delivery companies in the country.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'international_shipping',
    subcategory_name: 'International Shipping',
    location: 'Le Kram, Tunis',
    latitude: 36.8312,
    longitude: 10.3046,
    cover_image_url: 'https://picsum.photos/seed/tunisiaexpress-cover/800/400',
    logo_url: 'https://picsum.photos/seed/tunisiaexpress-logo/200/200',
    rating: 4.0,
    review_count: 430,
    is_featured: false,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: null,
      email: null,
      website: null,
      instagram_handle: null,
      facebook_name: 'SkyNetTunisiaExpress',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 37 },
      { stars: 4, percentage: 31 },
      { stars: 3, percentage: 18 },
      { stars: 2, percentage: 9 },
      { stars: 1, percentage: 5 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.0 },
      { name: 'Promptness', icon: 'clock-fast', rating: 4.1 },
    ],
  },
  {
    id: 'delivery_aramex',
    name: 'Aramex Tunisia',
    description: 'Global logistics giant present in over 60 countries, operating in Tunisia for 11+ years. Offers express delivery, freight forwarding, and complete e-commerce logistics solutions. The reference delivery company for businesses needing international reach.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'international_shipping',
    subcategory_name: 'International Shipping',
    location: 'Les Berges du Lac, La Marsa, Tunis',
    latitude: 36.8410,
    longitude: 10.2430,
    cover_image_url: 'https://picsum.photos/seed/aramex-cover/800/400',
    logo_url: 'https://picsum.photos/seed/aramex-logo/200/200',
    rating: 4.2,
    review_count: 890,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 71 160 800',
      email: null,
      website: 'https://www.aramex.com/tn/en',
      instagram_handle: 'aramex_tunisia',
      facebook_name: 'aramextunisia',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 43 },
      { stars: 4, percentage: 31 },
      { stars: 3, percentage: 15 },
      { stars: 2, percentage: 7 },
      { stars: 1, percentage: 4 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.2 },
      { name: 'Promptness', icon: 'clock-fast', rating: 4.1 },
    ],
  },
  {
    id: 'delivery_fedex',
    name: 'FedEx Tunisia',
    description: 'World-leading express delivery company operating in Tunisia. FedEx International Priority offers the fastest international shipping in 1-4 business days. Full range of shipping, tracking, and customs clearance services.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'international_shipping',
    subcategory_name: 'International Shipping',
    location: '72 Rue des Mineraux, Charguia 1, Tunis',
    latitude: 36.8350,
    longitude: 10.1990,
    cover_image_url: 'https://picsum.photos/seed/fedex-cover/800/400',
    logo_url: 'https://picsum.photos/seed/fedex-logo/200/200',
    rating: 4.4,
    review_count: 720,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: null,
      email: null,
      website: 'https://www.fedex.com/en-tn/home.html',
      instagram_handle: null,
      facebook_name: null,
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 48 },
      { stars: 4, percentage: 30 },
      { stars: 3, percentage: 13 },
      { stars: 2, percentage: 6 },
      { stars: 1, percentage: 3 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.4 },
      { name: 'Promptness', icon: 'clock-fast', rating: 4.5 },
    ],
  },
  {
    id: 'delivery_dhl',
    name: 'DHL Express Tunisia',
    description: 'Global express delivery and logistics leader operating in Tunisia through Sindbad Group. Offers international express shipping, customs brokerage, and door-to-door delivery. Service point located at Charguia 1 near Tunis Airport.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'international_shipping',
    subcategory_name: 'International Shipping',
    location: '2 Rue Sinbad, Charguia 1, Tunis',
    latitude: 36.8345,
    longitude: 10.1980,
    cover_image_url: 'https://picsum.photos/seed/dhl-cover/800/400',
    logo_url: 'https://picsum.photos/seed/dhl-logo/200/200',
    rating: 4.5,
    review_count: 950,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 31 323 334',
      email: null,
      website: 'https://mydhl.express.dhl/tn/en/home.html',
      instagram_handle: null,
      facebook_name: 'dhltunisie',
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 50 },
      { stars: 4, percentage: 29 },
      { stars: 3, percentage: 12 },
      { stars: 2, percentage: 6 },
      { stars: 1, percentage: 3 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.5 },
      { name: 'Promptness', icon: 'clock-fast', rating: 4.6 },
    ],
  },
  {
    id: 'delivery_ups',
    name: 'UPS Tunisia',
    description: 'Global shipping and logistics leader with offices in Tunisia. Provides worldwide express delivery, freight, supply chain management, and customs brokerage. Offices in Charguia and Enfidha Airport.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'international_shipping',
    subcategory_name: 'International Shipping',
    location: '21 Rue des Entrepreneurs, Charguia 2, Tunis',
    latitude: 36.8375,
    longitude: 10.2045,
    cover_image_url: 'https://picsum.photos/seed/ups-cover/800/400',
    logo_url: 'https://picsum.photos/seed/ups-logo/200/200',
    rating: 4.3,
    review_count: 610,
    is_featured: true,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: '+216 82 107 777',
      email: null,
      website: 'https://www.ups.com/tn/en/home',
      instagram_handle: null,
      facebook_name: null,
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 46 },
      { stars: 4, percentage: 30 },
      { stars: 3, percentage: 14 },
      { stars: 2, percentage: 7 },
      { stars: 1, percentage: 3 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.3 },
      { name: 'Promptness', icon: 'clock-fast', rating: 4.4 },
    ],
  },
  {
    id: 'delivery_chronopost',
    name: 'Chronopost Tunisia',
    description: 'French express parcel delivery service operating in Tunisia for international shipments. Specializes in time-sensitive deliveries between Tunisia and Europe, offering next-day and express delivery options.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'international_shipping',
    subcategory_name: 'International Shipping',
    location: 'Tunis, Tunisia',
    latitude: 36.8120,
    longitude: 10.1790,
    cover_image_url: 'https://picsum.photos/seed/chronopost-cover/800/400',
    logo_url: 'https://picsum.photos/seed/chronopost-logo/200/200',
    rating: 4.1,
    review_count: 280,
    is_featured: false,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: null,
      email: null,
      website: 'https://www.chronopost.fr',
      instagram_handle: null,
      facebook_name: null,
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 40 },
      { stars: 4, percentage: 30 },
      { stars: 3, percentage: 17 },
      { stars: 2, percentage: 8 },
      { stars: 1, percentage: 5 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 4.1 },
      { name: 'Promptness', icon: 'clock-fast', rating: 4.2 },
    ],
  },
  {
    id: 'delivery_colissimo',
    name: 'Colissimo Tunisia',
    description: 'La Poste group\'s international parcel delivery service available in Tunisia. Offers affordable international shipping with tracking, primarily for shipments between Tunisia and France/Europe. Popular for e-commerce and personal parcels.',
    category_id: 'delivery_company',
    category_name: 'Delivery Company',
    subcategory_id: 'international_shipping',
    subcategory_name: 'International Shipping',
    location: 'Tunis, Tunisia',
    latitude: 36.8000,
    longitude: 10.1860,
    cover_image_url: 'https://picsum.photos/seed/colissimo-cover/800/400',
    logo_url: 'https://picsum.photos/seed/colissimo-logo/200/200',
    rating: 3.9,
    review_count: 190,
    is_featured: false,
    is_open: true,
    owner_id: 'system',
    contact: {
      phone: null,
      email: null,
      website: 'https://www.colissimo.fr',
      instagram_handle: null,
      facebook_name: null,
      tiktok_handle: null,
    },
    delivery_services: [],
    menu_categories: [],
    rating_distribution: [
      { stars: 5, percentage: 34 },
      { stars: 4, percentage: 29 },
      { stars: 3, percentage: 20 },
      { stars: 2, percentage: 11 },
      { stars: 1, percentage: 6 },
    ],
    category_ratings: [
      { name: 'Service', icon: 'shield-account', rating: 3.9 },
      { name: 'Promptness', icon: 'clock-fast', rating: 3.8 },
    ],
  },
];

// ── Seed Functions ──────────────────────────────────────────────────────────

async function seedCategories() {
  console.log('Seeding categories...');
  for (const cat of CATEGORIES_DATA) {
    const { id, subcategories, ratingCriteria, ...rest } = cat;

    // Write category document
    await setDoc(doc(db, 'categories', id), {
      ...rest,
      subcategories: subcategories.map((s) => ({ id: s.id, name: s.name, category_id: id })),
      rating_criteria: ratingCriteria.map((r) => ({ key: r.key, label: r.label, icon: r.icon })),
      created_at: serverTimestamp(),
      updated_at: serverTimestamp(),
    });

    // Write each subcategory as its own document for easy querying
    for (const sub of subcategories) {
      await setDoc(doc(db, 'categories', id, 'subcategories', sub.id), {
        name: sub.name,
        category_id: id,
        created_at: serverTimestamp(),
      });
    }

    console.log(`  + Category: ${cat.name} (${subcategories.length} subcategories, ${ratingCriteria.length} criteria)`);
  }
  console.log(`Seeded ${CATEGORIES_DATA.length} categories.`);
}

async function seedBusinesses() {
  console.log('Seeding businesses...');
  for (const biz of BUSINESSES) {
    const { id, ...data } = biz;
    await setDoc(doc(db, 'businesses', id), {
      ...data,
      created_at: serverTimestamp(),
      updated_at: serverTimestamp(),
    });
    console.log(`  + Business: ${biz.name}`);
  }
  console.log(`Seeded ${BUSINESSES.length} businesses.`);
}

async function main() {
  console.log('=== Firestore Seed Script ===');
  console.log(`Project: ${firebaseConfig.projectId}`);
  console.log('');

  try {
    await seedCategories();
    console.log('');
    await seedBusinesses();
    console.log('');
    console.log('Seed complete!');
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }

  process.exit(0);
}

main();
